name: Daily Commit

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Increment a counter in a file
      - name: Updates repo
        run: |
          git fetch
          git pull -r
      - name: Update counter
        run: |
          echo "Daily Commit number $(cat counter.txt)" >> file.txt
          echo $((1 + $(cat counter.txt))) > counter.txt

      - name: Commit and Push
        run: |
          git config --global user.name 'Santiago Quintero'
          git config --global user.email 'santiagoquinteroq@gmail.com'
          git add .
          git commit -m "Daily Commit number $(cat counter.txt)"
          git push
